apiVersion: v1
kind: Pod
metadata:
  name: kfp-test
  namespace: kubeflow
spec:
  containers:
  - name: kfp-client
    image: okadak86/quakeflow-miniconda:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: workdir
      mountPath: /home/jovyan/work
  volumes:
  - name: workdir
    hostPath:
      path: /home/docker/work/
      type: DirectoryOrCreate