all:
  children:
    vrt_servers:
      hosts:
        vrt_server:
          ansible_host: "{{ lookup('env', 'TF_VAR_server_ip') | default('127.0.0.1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_become: yes
          ansible_become_method: sudo
      vars:
        # CUDA関連の変数
        cuda_version: "12.9"
        cuda_arch: "12.9"
        gpu_driver_version: "latest"
        
        # システム設定
        timezone: "Asia/Tokyo"
        locale: "en_US.UTF-8"
        
        # パッケージ管理
        apt_cache_valid_time: 3600
